import React from "react";
import { motion } from "framer-motion";
import { ShieldAlert, Lock, Database } from "lucide-react";
import Container from "../components/layout/Container";

export default function Privacy() {
  const lastUpdated = "April 2026";

  return (
    <div style={{ background: "#060a06", color: "white", minHeight: "100vh" }}>
      
      {/* ── HEADER (DARK) ── */}
      <section style={{ position: "relative", padding: "120px 0 80px", background: "linear-gradient(180deg, #0a1a0a 0%, #060a06 100%)", textAlign: "center", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)", width: "800px", height: "400px", background: "radial-gradient(ellipse, rgba(34,197,94,0.1) 0%, transparent 60%)", pointerEvents: "none" }} />
        
        <Container style={{ position: "relative", zIndex: 1 }}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", padding: "6px 14px", background: "rgba(34,197,94,0.08)", border: "1px solid rgba(34,197,94,0.2)", borderRadius: "100px", marginBottom: "24px" }}>
              <ShieldAlert size={12} color="#22c55e" />
              <span style={{ fontSize: "12px", fontWeight: 700, color: "#22c55e", textTransform: "uppercase", letterSpacing: "1px" }}>Legal & Compliance</span>
            </div>
            <h1 style={{ fontSize: "clamp(40px, 6vw, 64px)", fontWeight: 900, letterSpacing: "-2px", marginBottom: "24px", color: "white", lineHeight: 1.1 }}>
              Privacy <span style={{ color: "#22c55e" }}>Policy</span>
            </h1>
            <p style={{ fontSize: "16px", color: "rgba(255,255,255,0.4)", margin: "0 auto" }}>
              Last updated: {lastUpdated}
            </p>
          </motion.div>
        </Container>
      </section>

      {/* ── DOC CONTENT (WHITE SECTION) ── */}
      <section style={{ padding: "80px 0 120px", background: "#f8fafc", color: "#0a0e0a", borderRadius: "40px 40px 0 0", minHeight: "500px", zIndex: 2, position: "relative" }}>
        <Container>
          <div style={{ maxWidth: "800px", margin: "0 auto" }}>
            
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "20px", marginBottom: "60px" }}>
              <div style={{ background: "white", padding: "24px", borderRadius: "16px", border: "1px solid rgba(0,0,0,0.05)", display: "flex", alignItems: "center", gap: "16px" }}>
                <div style={{ background: "rgba(34,197,94,0.1)", p: "12px", borderRadius: "10px", color: "#16a34a", padding: "10px" }}><Lock size={20} /></div>
                <div><h4 style={{ fontSize: "14px", fontWeight: 800 }}>End-to-End Encrypted</h4><p style={{ fontSize: "12px", color: "rgba(0,0,0,0.4)", marginTop: "2px" }}>For all farm telemetry data</p></div>
              </div>
              <div style={{ background: "white", padding: "24px", borderRadius: "16px", border: "1px solid rgba(0,0,0,0.05)", display: "flex", alignItems: "center", gap: "16px" }}>
                <div style={{ background: "rgba(34,197,94,0.1)", p: "12px", borderRadius: "10px", color: "#16a34a", padding: "10px" }}><Database size={20} /></div>
                <div><h4 style={{ fontSize: "14px", fontWeight: 800 }}>Sri Lanka Hosted</h4><p style={{ fontSize: "12px", color: "rgba(0,0,0,0.4)", marginTop: "2px" }}>Compliance with local regulations</p></div>
              </div>
            </div>

            <div className="legal-content">
              <h3>1. Introduction</h3>
              <p>GreenAyu ("we", "our", "us") respects your privacy and is committed to protecting it through our compliance with this policy. This policy describes the types of information we may collect from you or that you may provide when you access our AI Diagnostic and Telemetry platform (the "Platform"), and our practices for collecting, using, maintaining, protecting, and disclosing that information.</p>

              <h3>2. Data We Collect</h3>
              <p>We collect several types of information from and about users of our Platform, including:</p>
              <ul>
                <li><strong>Personal Identifiers:</strong> Name, postal address, e-mail address, telephone number, or any other identifier by which you may be contacted online or offline.</li>
                <li><strong>Agricultural Data:</strong> Images of leaves or plant components uploaded for diagnostics, which may inadvertently contain geographical metadata (EXIF).</li>
                <li><strong>Telemetry Data:</strong> Environmental parameters generated by your hardware sensors (e.g., NPK levels, humidity) if you use our IoT modules.</li>
              </ul>

              <h3>3. How We Use Your Data</h3>
              <p>We use information that we collect about you or that you provide to us:</p>
              <ul>
                <li>To present our Platform and its contents to you.</li>
                <li>To run computer vision diagnostics and yield prediction models. <em>Note: Uploaded images are anonymized before being fed into retraining pipelines unless you opt out.</em></li>
                <li>To notify you about changes to our Platform or any products or services we offer or provide though it.</li>
                <li>To process AI credit deductions and transaction auditing.</li>
              </ul>

              <h3>4. Data Security</h3>
              <p>We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. All information you provide to us is stored on our secure servers behind firewalls. Any payment transactions and sensor data streams are encrypted in transit.</p>
              
              <h3>5. Changes to Our Privacy Policy</h3>
              <p>It is our policy to post any changes we make to our privacy policy on this page. If we make material changes to how we treat our users' personal information, we will notify you through a notice on the Platform home page or via email.</p>

            </div>

          </div>
        </Container>
      </section>

      <style>{`
        .legal-content h3 {
          font-size: 20px;
          font-weight: 800;
          color: #060a06;
          margin-top: 48px;
          margin-bottom: 16px;
        }
        .legal-content h3:first-child { margin-top: 0; }
        .legal-content p {
          font-size: 15px;
          line-height: 1.8;
          color: rgba(0,0,0,0.65);
          margin-bottom: 24px;
        }
        .legal-content ul {
          padding-left: 20px;
          margin-bottom: 32px;
        }
        .legal-content li {
          font-size: 15px;
          line-height: 1.7;
          color: rgba(0,0,0,0.65);
          margin-bottom: 12px;
        }
        .legal-content strong { color: #060a06; font-weight: 700; }
      `}</style>
      
    </div>
  );
}
